### PR TITLE
add time since record start marker to the output

### PR DESCRIPTION
**Pull request by romantolkachyov**
Hi! This adds `[HH:ss]` marker right before the user name in the output. Looks useful in general if you want to build navigation over video etc.

### CODE REVIEW

**Comment by vivek-nexus** [comment]
@romantolkachyov could you explain in more detail on why you would prefer relative timestamp (time elapsed since start of meeting) over absolute timestamp?

**Comment by romantolkachyov** [comment]
@vivek-nexus sorry for the long reply. I used relative timestamp because that's my target format. But you're right, it would probably be much better to store absolute timestamps in general and calculate relative timestamp if needed on complete transcription.
On the other hand, video subtitles use relative format too.

**Comment by vivek-nexus** [comment]
@romantolkachyov understood the use case you are looking at. Video subtitle files have a very specific and singular purpose, which justifies the use of relative timestamp. I will stick to absolute timestamps, to prevent loss of information at source.

For your use case, may be you could write a local script to convert absolute timestamps to relative ones, along with file format conversion from txt to srt, if needed?

**Comment by romantolkachyov** [comment]
Sure, it works

**Pull request merged**
